apiVersion: v1
kind: Service
metadata:
  name: spark-master
  labels:
    app: spark
spec:
  type: LoadBalancer
  ports:
    - name: spark-master
      port: 7077
      targetPort: 7077
    - name: spark-ui
      port: 8080
      targetPort: 8080
  selector:
    app: spark
    role: master
