apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  labels:
    app: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: master
  template:
    metadata:
      labels:
        app: spark
        role: master
    spec:
      containers:
        - name: spark-master
          image: bitnami/spark:3.5.1
          env:
            - name: SPARK_MODE
              value: "master"  # Set mode to master
          ports:
            - containerPort: 7077
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    app: spark
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      containers:
        - name: spark-worker
          image: bitnami/spark:3.5.1
          env:
            - name: SPARK_MODE
              value: "worker"  # Set mode to worker
            - name: SPARK_MASTER_URL
              value: "spark://spark-master:7077"
          resources:
            requests:
              memory: "4Gi"   # Minimum memory per pod
              cpu: "2"         # Minimum CPU per pod
            limits:
              memory: "8Gi"    # Maximum memory per pod
              cpu: "4"         # Maximum CPU per pod
          ports:
            - containerPort: 8081
